export { Hero } from './Hero';
export { About } from './About';
export { Experience } from './Experience';
export { Skills } from './Skills';
export { WorkProjects } from './WorkProjects';
export { PersonalProjects } from './PersonalProjects';
export { Education } from './Education';
export { Volunteering } from './Volunteering';
export { Contact } from './Contact';
